#!/usr/bin/env bash
# Tier 1: Validate the Codex slot runtime helper normalizes raw Codex runs.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/test-helpers.sh"

FAILED=0
RUNNER_PATH="$SKILL_DIR/scripts/codex-slot-runner.py"
ITEM_FIXTURE="$SKILL_DIR/tests/fixtures/codex-item-and-turn.jsonl"
TURN_COMMAND_FIXTURE="$SKILL_DIR/tests/fixtures/codex-turn-command-only.jsonl"
TMP_ROOT=$(mktemp -d)
FAKE_BIN_DIR="$TMP_ROOT/bin"
REPO_DIR="$TMP_ROOT/repo"
PROMPT_FILE="$TMP_ROOT/prompt.txt"

cleanup() {
    rm -rf "$TMP_ROOT"
}
trap cleanup EXIT

mkdir -p "$FAKE_BIN_DIR" "$REPO_DIR"
cat > "$PROMPT_FILE" <<'EOF'
Implement the token bucket.
EOF

cat > "$FAKE_BIN_DIR/codex" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

mode="${FAKE_CODEX_MODE:-agent}"
case "$mode" in
  agent)
    cat "$FAKE_CODEX_FIXTURE"
    ;;
  synth)
    printf 'generated by fake codex\n' > "${FAKE_CODEX_OUTPUT_FILE:?}"
    cat "$FAKE_CODEX_FIXTURE"
    ;;
  *)
    echo "unknown fake codex mode: $mode" >&2
    exit 1
    ;;
esac
EOF
chmod +x "$FAKE_BIN_DIR/codex"

git -C "$REPO_DIR" init >/dev/null 2>&1
git -C "$REPO_DIR" config user.email "slot-machine-tests@example.com"
git -C "$REPO_DIR" config user.name "Slot Machine Tests"
printf 'base\n' > "$REPO_DIR/README.md"
git -C "$REPO_DIR" add README.md
git -C "$REPO_DIR" commit -m "init" >/dev/null 2>&1

echo "=== Codex Slot Runner: Script Exists ==="
if [ -x "$RUNNER_PATH" ]; then
    echo "  [PASS] Codex slot runner exists and is executable"
else
    echo "  [FAIL] Missing executable helper: $RUNNER_PATH"
    FAILED=$((FAILED + 1))
fi

echo ""
echo "=== Codex Slot Runner: Structured Agent Message ==="
if [ -x "$RUNNER_PATH" ]; then
    AGENT_RESULT="$TMP_ROOT/agent-result.json"
    AGENT_EVENTS="$TMP_ROOT/agent-events.jsonl"
    AGENT_STDERR="$TMP_ROOT/agent-stderr.txt"
    AGENT_REPORT="$TMP_ROOT/agent-report.md"

    PATH="$FAKE_BIN_DIR:$PATH" \
    FAKE_CODEX_MODE="agent" \
    FAKE_CODEX_FIXTURE="$ITEM_FIXTURE" \
    python3 "$RUNNER_PATH" \
        --cwd "$REPO_DIR" \
        --prompt-file "$PROMPT_FILE" \
        --events-file "$AGENT_EVENTS" \
        --stderr-file "$AGENT_STDERR" \
        --result-file "$AGENT_RESULT" \
        --report-file "$AGENT_REPORT" >/dev/null 2>&1 || true

    AGENT_JSON=$(cat "$AGENT_RESULT" 2>/dev/null || true)
    assert_contains "$AGENT_JSON" '"status": "DONE"' \
        "Structured report preserves DONE status" || FAILED=$((FAILED + 1))
    assert_contains "$AGENT_JSON" '"thread_id": "thread-test"' \
        "Structured report captures Codex thread id" || FAILED=$((FAILED + 1))
    assert_contains "$AGENT_JSON" '"report_source": "agent_message"' \
        "Structured report records agent_message source" || FAILED=$((FAILED + 1))
    assert_contains "$(cat "$AGENT_REPORT" 2>/dev/null || true)" "## Implementer Report" \
        "Structured report writes normalized markdown report" || FAILED=$((FAILED + 1))
fi

echo ""
echo "=== Codex Slot Runner: Post-Run Inspection Synthesis ==="
if [ -x "$RUNNER_PATH" ]; then
    SYNTH_RESULT="$TMP_ROOT/synth-result.json"
    SYNTH_EVENTS="$TMP_ROOT/synth-events.jsonl"
    SYNTH_STDERR="$TMP_ROOT/synth-stderr.txt"
    SYNTH_REPORT="$TMP_ROOT/synth-report.md"
    SYNTH_OUTPUT="$REPO_DIR/generated.txt"

    PATH="$FAKE_BIN_DIR:$PATH" \
    FAKE_CODEX_MODE="synth" \
    FAKE_CODEX_FIXTURE="$TURN_COMMAND_FIXTURE" \
    FAKE_CODEX_OUTPUT_FILE="$SYNTH_OUTPUT" \
    python3 "$RUNNER_PATH" \
        --cwd "$REPO_DIR" \
        --prompt-file "$PROMPT_FILE" \
        --events-file "$SYNTH_EVENTS" \
        --stderr-file "$SYNTH_STDERR" \
        --result-file "$SYNTH_RESULT" \
        --report-file "$SYNTH_REPORT" >/dev/null 2>&1 || true

    SYNTH_JSON=$(cat "$SYNTH_RESULT" 2>/dev/null || true)
    SYNTH_REPORT_TEXT=$(cat "$SYNTH_REPORT" 2>/dev/null || true)
    assert_contains "$SYNTH_JSON" '"status": "DONE"' \
        "Post-run inspection promotes successful changed-file run to DONE" || FAILED=$((FAILED + 1))
    assert_contains "$SYNTH_JSON" '"thread_id": "thread-synth"' \
        "Post-run inspection keeps Codex thread id" || FAILED=$((FAILED + 1))
    assert_contains "$SYNTH_JSON" '"report_source": "post_run_inspection"' \
        "Post-run inspection marks synthesized report source" || FAILED=$((FAILED + 1))
    assert_contains "$SYNTH_JSON" '"generated.txt"' \
        "Post-run inspection records changed files" || FAILED=$((FAILED + 1))
    assert_contains "$SYNTH_REPORT_TEXT" "turn.completed without a structured agent_message report" \
        "Post-run inspection records missing structured report concern" || FAILED=$((FAILED + 1))
fi

echo ""
echo "=== Codex Slot Runner Tests Complete ==="
echo "Failures: $FAILED"
exit $FAILED
